# -*- coding: utf-8 -*-
"""Creacion Base de datos Ficticia.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GSt4CYQst2zLGOE0XnzeFU0QM3MqGZBq

# Esto es un ejercio para la creación de una base de datos ficticia de una tienda la cual vende 4 tipos de productos.



1.   Electrodomesticos
1.   Ropa
2.   Bicicletas
2.   Comida

Creado y desarrolado por: [BOSS LEO PAPI](https://www.linkedin.com/in/leo-hernandez-datasciencee/)
"""

#Importación de librerias a usar
import pandas as pd
import random
!pip install faker
from faker import Faker

"""1. La tabla clientes quiero que tenga estos campos:

* ID, usar numeros con una longitu de 10 cifras
* Nombre, Nombres en Idioma español
* Edad, edades desde 15 hasta maximo 100
* Correo electronico, correcos con las 4 primeras letras del hombre y 2 numeros aleatorios
* Telefono, números con el indicativo +57 para saber que son Colombianos.

2. La tabla Productos quiero que tenga estos campos:
* ID
* Categoria, estas son las categorias:
Ciclismo:
MTB, Ruta, Gravel

Electrodomesticos:
Pc, Tablet, Celular

Ropa:
Formal, Casual, Exclusiva

Comida:
Vegana, Italiana, Francesa

* Precio, en esta categoria poner precio en dolares, aleatoriamente desde 50 USD hasta 8900 USD

3. La tabla Ventas quiero que tenga estos campos:

* ID Venta
* Fecha, en orden Año/Mes/Día
* ID Cliente, tiene que ir realacionado con el ID de la tabla clientes
* ID Producto, tiene que ir realacionado con el ID de la tabla productos
* Cantidad, Valores de venta de cada uno de los productos

4. La tabla Opiniones quiero que tenga estos campos:

* ID opinión
* ID Cliente, tiene que ir relacionado con el ID de la tabla clientes
* ID Producto, tiene que ir relacionado con el ID de la tabla de producto
* Opinión:
None
Mala
Regular
Aceptable
Buena
Excelente
"""

# Crear instancia de Faker para la generación del los nombres:
faker = Faker('es_ES')

# Creamos la tabla Clientes:
clientes_data = {
    'ID': [str(random.randint(1000000000, 9999999999)) for _ in range(100)],
    'Nombre': [faker.first_name() for _ in range(100)],
    'Edad': [random.randint(15, 100) for _ in range(100)],
    'Correo electrónico': ['{}{}@ejemplo.com'.format(nombre[:4].lower(), random.randint(10, 99)) for nombre in [n[:4] for n in clientes_data['Nombre']]],
    'Teléfono': ['+57{}'.format(random.randint(1000000, 9999999)) for _ in range(100)],
}

clientes_df = pd.DataFrame(clientes_data)
display(clientes_df)

# Crear tabla Productos
categorias = ['Ciclismo', 'Electrodomesticos', 'Ropa', 'Comida']
productos_data = {
    'ID': range(1, 101),
    'Categoria': [random.choice(categorias) for _ in range(100)],
    'Precio': [],
}

for cat in productos_data['Categoria']:
    if cat != 'Comida':
        productos_data['Precio'].append(random.randint(50, 8900))
    else:
        productos_data['Precio'].append(random.uniform(50, 8900))

productos_df = pd.DataFrame(productos_data)
display(productos_df)

# Creamos la tabla Ventas:
ventas_data = {
    'ID Venta': range(1, 101),
    'Fecha': pd.date_range(start='1/1/2023', periods=100),
    'ID Cliente': [random.choice(clientes_data['ID']) for _ in range(100)],
    'ID Producto': [random.choice(productos_data['ID']) for _ in range(100)],
    'Cantidad': [random.randint(1, 10) for _ in range(100)],
}

ventas_df = pd.DataFrame(ventas_data)
display(ventas_df)

# Creamos la tabla Opiniones:
opiniones_data = {
    'ID Opinión': range(1, 101),
    'ID Cliente': [random.choice(clientes_data['ID']) for _ in range(100)],
    'ID Producto': [random.choice(productos_data['ID']) for _ in range(100)],
    'Opinión': [random.choice(['None', 'Mala', 'Regular', 'Aceptable', 'Buena', 'Excelente']) for _ in range(100)],
}

opiniones_df = pd.DataFrame(opiniones_data)
display(opiniones_df)

from google.colab import files

# Exportar a Excel
clientes_df.to_excel('clientes.xlsx', index=False)
#productos_df.to_excel('productos.xlsx', index=False)
#ventas_df.to_excel('ventas.xlsx', index=False)
#opiniones_df.to_excel('opiniones.xlsx', index=False)

# Descargar los archivos de Excel
files.download('clientes.xlsx')
#files.download('productos.xlsx')
#files.download('ventas.xlsx')
#files.download('opiniones.xlsx')